//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestHookah.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogArticles
    {
        public int BlogArticleId { get; set; }
        public string BlogArticleName { get; set; }
        public string BlogArticleShortDescription { get; set; }
        public System.DateTime BlogArticleCreationDate { get; set; }
        public string BlogArticleAuthor { get; set; }
        public string BlogArticleContent { get; set; }
        public string BlogArticleImagePath { get; set; }
    }
}
