//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestHookah.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offers
    {
        public int OfferId { get; set; }
        public string OfferName { get; set; }
        public string OfferShortDescription { get; set; }
        public System.DateTime OfferExpirationDate { get; set; }
    }
}
