//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAtr.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReserve
    {
        public int RoomReserveId { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Arrive { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<int> Adults { get; set; }
        public Nullable<int> Children { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
