//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAtr.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [AppointValidate]
    public partial class Rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rooms()
        {
            this.RoomOptions = new HashSet<RoomOptions>();
            this.RoomReserve = new HashSet<RoomReserve>();
            this.Options = new HashSet<Options>();
        }
    
        [HiddenInput(DisplayValue =false)]
        public int RoomId { get; set; }

        [ValidateSettings(ErrorMessage ="Цена не должна быть меньше 0")]
        public double Price { get; set; }

        [Required(ErrorMessage ="Название комнаты обязательное")]
        [DisplayName("Название комнаты")]
        public string Name { get; set; }

        [Required]
        [Remote("IsPicEvent", "Room", ErrorMessage ="Путь указан неверно")]
        public string PathBasePicture { get; set; }
        public int RoomTypeId { get; set; }


        [Range(1, 12, ErrorMessage = "Нет больше 12 этажей")]
        public int Floor { get; set; }

        [StringLength(50, MinimumLength =3, ErrorMessage ="*")]
        public string Description { get; set; }

        [ScaffoldColumn(false)]
        [DataType(DataType.EmailAddress)]
        public string EmailAddress { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [System.ComponentModel.DataAnnotations.Compare("Password")]
        public string RePassword { get; set; }



        //[Range(typeof(bool), "true", "true", ErrorMessage = "Вы должны согласиться с условием")]
        public bool Terms { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomOptions> RoomOptions { get; set; }
        public virtual RoomType RoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReserve> RoomReserve { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Options> Options { get; set; }
    }
}
